name: Build README
on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        # necessary for github-action-til-autoformat-readme
        fetch-depth: 0
    - name: Autoformat README
      uses: cflynn07/github-action-til-autoformat-readme@1.2.4
      with:
        description: |
          We constantly learn new things. This is a repo to share those learnings. TILs are short Markdown documents (a few sentences + example code) explaining concepts, bits of syntax, commands, or tips we've recently learned.
          - For more posts, check [Blog][1] and [xLog][2]
          - using [cflynn07/github-action-til-autoformat-readme][3] to automatically generate a README.md from a repo of TILs
        footer: |
          [1]: https://joytown99.top
          [2]: https://joytown99.xlog.app
          [3]: https://github.com/cflynn07/til-autoformat-action-example
        list_most_recent: 3 # optional, lists most recent TILS below description
        #date_format: "2020 Jan 15:04" # optional, must align to https://golang.org/pkg/time/#Time.Format
